#!/bin/bash

character_template_1 () {
    character_name_1="El Narcisista"
    hp=100
    atk_p=10
    atk_m=1
    def_p=5
    def_m=5
    speed=12
    crit_r=5
    crit_h=150
}

character_skillset_1() {
    echo 
}